FROM fitbur/ubuntu

MAINTAINER Sharmarke Aden, saden1@gmail.com
ENV _VERSION 14.04

# Install core utils needed to build from source
RUN apt-get install -y build-essential tcl
RUN apt-get -y clean
RUN apt-get -y autoremove

